# Generated by Django 2.1.3 on 2018-11-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'В наличии'), (1, 'Нет в наличии'), (2, 'Ожидается'), (3, 'Не ожидается'), (4, 'Снято с продаж')], default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
